# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt:
  switch:
    - name: "LED 1"
      unique_id: led 1
      command_topic: "home/esp32/led1/set"
      payload_on: "ON"
      payload_off: "OFF"

    - name: "LED 2"
      unique_id: led 2
      command_topic: "home/esp32/led2/set"
      payload_on: "ON"
      payload_off: "OFF"

    - name: "Cua Ra Vao (Servo)"
      unique_id: door_servo_lock
      command_topic: "home/esp32/servo/set"
      state_topic: "home/esp32/servo/state"
      payload_on: "OPEN"
      payload_off: "CLOSE"
      state_on: "OPEN"
      state_off: "CLOSE"
      icon: "mdi:door-closed"

