# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt:
  switch:
    - name: "LED 1"
      unique_id: led 1
      command_topic: "home/esp32/led1/set"
      payload_on: "ON"
      payload_off: "OFF"

    - name: "LED Phong Khach"
      unique_id: led_phong_khach
      command_topic: "home/esp32/led_phong_khach/set"
      payload_on: "ON"
      payload_off: "OFF"

    - name: "Cua Ra Vao (Servo)"
      unique_id: door_servo_lock
      command_topic: "home/esp32/servo/set"
      state_topic: "home/esp32/servo/state"
      payload_on: "OPEN"
      payload_off: "CLOSE"
      state_on: "OPEN"
      state_off: "CLOSE"
      icon: "mdi:door-closed"

    - name: "Quat Lam Mat"
      unique_id: esp32_fan_switch
      command_topic: "home/esp32/fan/set"
      state_topic: "home/esp32/fan/state"
      payload_on: "ON"
      payload_off: "OFF"
      icon: "mdi:fan"

    - name: "Che Do Quat Tu Dong"
      unique_id: esp32_fan_mode_switch
      command_topic: "home/esp32/fan/mode/set"
      state_topic: "home/esp32/fan/mode/state"
      payload_on: "auto"
      payload_off: "manual"
      state_on: "auto"
      state_off: "manual"
      icon: "mdi:robot"

    - name: "Cua So (Servo)"
      unique_id: window_servo_lock
      command_topic: "home/esp32/window/set"
      state_topic: "home/esp32/window/state"
      payload_on: "OPEN"
      payload_off: "CLOSE"
      state_on: "OPEN"
      state_off: "CLOSE"
      icon: "mdi:window-closed"

    - name: "Đèn Bếp"
      unique_id: esp32_led_bep
      command_topic: "home/esp32/led_bep/set"
      payload_on: "ON"
      payload_off: "OFF"
      icon: "mdi:wall-sconce-flat"

    - name: "Đèn Phòng Ngủ"
      unique_id: esp32_led_phong_ngu
      command_topic: "home/esp32/led_phong_ngu/set"
      payload_on: "ON"
      payload_off: "OFF"
      icon: "mdi:bed"

    - name: "Đèn Nhà Vệ Sinh"
      unique_id: esp32_led_nha_ve_sinh
      command_topic: "home/esp32/led_nha_ve_sinh/set"
      state_topic: "home/esp32/led_nha_ve_sinh/state"
      payload_on: "ON"
      payload_off: "OFF"
      icon: "mdi:shower-head"

  binary_sensor:
    - name: "Cam Bien Mua"
      state_topic: "home/esp32/sensor/rain"
      payload_on: "ON"
      payload_off: "OFF"
      device_class: "moisture"
      unique_id: esp32_rain_sensor

    - name: "Cảnh Báo Động Đất"
      state_topic: "home/esp32/sensor/earthquake"
      payload_on: "ON"
      payload_off: "OFF"
      device_class: "vibration"
      unique_id: esp32_earthquake_sensor

    - name: "Cảnh Báo Khí Gas"
      state_topic: "home/esp32/sensor/gas"
      payload_on: "ON"
      payload_off: "OFF"
      device_class: "gas"
      unique_id: esp32_gas_sensor

  sensor:
    - name: "Nhiet Do"
      state_topic: "home/esp32/sensor/temperature"
      unit_of_measurement: "°C"
      device_class: "temperature"
      unique_id: esp32_temperature

    - name: "Do Am"
      state_topic: "home/esp32/sensor/humidity"
      unit_of_measurement: "%"
      device_class: "humidity"
      unique_id: esp32_humidity

switch:
  - platform: group
    name: "Tất Cả Đèn"
    entities:
      - switch.led_1
      - switch.led_phong_khach
      - switch.den_bep
      - switch.den_phong_ngu
      - switch.den_nha_ve_sinh

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
    - 172.16.0.0/12
    - 192.168.0.0/16
